<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="shiv-Inspiron-N5110" failures="1" tests="3" name="Default test" time="18.71" errors="0" timestamp="2025-06-21T09:19:00 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.532"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.536"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="17.928">
    <failure type="java.lang.AssertionError" message="[VERIFICATION - FAIL] failed message">
      <![CDATA[java.lang.AssertionError: [VERIFICATION - FAIL] failed message
at org.testng.Assert.fail(Assert.java:111)
at customized.WrappedAssert.assertTrue(WrappedAssert.java:41)
at stepDefinitions.Pagec.read_the_title_of_page(Pagec.java:12)
at âœ½.read the title of page(classpath:features//firstFeaturefile.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
