<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="shiv-Inspiron-N5110" failures="2" tests="2" name="runner.ReRunTestRunner" time="62.021" errors="0" timestamp="2025-06-28T16:03:37 IST" skipped="0">
  <testcase classname="runner.ReRunTestRunner" name="runScenario" time="43.315">
    <failure message="Unable to find &#039;13677&#039; with locator &#039;By.linkText: 13677&#039;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Unable to find '13677' with locator 'By.linkText: 13677'
at org.testng.Assert.fail(Assert.java:111)
at utils.SeleniumUtils.getElement(SeleniumUtils.java:55)
at utils.SeleniumUtils.click(SeleniumUtils.java:165)
at Pages.CommonPage.clickOnlink(CommonPage.java:51)
at stepDefinitions.CommonSteps.user_clicks_on_link_on_page(CommonSteps.java:46)
at ✽.user clicks on "13677" link on "Account Overview" page(classpath:features//firstFeaturefile.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.ReRunTestRunner" name="runScenario" time="18.706">
    <failure message="[VERIFICATION - FAIL] validating title. EXPECTED [Welcome shivsahilguleri]  ACTUAL [Signing up is easy!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: [VERIFICATION - FAIL] validating title. EXPECTED [Welcome shivsahilguleri]  ACTUAL [Signing up is easy!]
at org.testng.Assert.fail(Assert.java:111)
at customized.WrappedAssert.assertEquals(WrappedAssert.java:58)
at stepDefinitions.LandingSteps.user_validating_userid_on_login_page(LandingSteps.java:18)
at ✽.user validating userid "shivsahilguleri" is present on login page(classpath:features//firstFeaturefile.feature:14)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.ReRunTestRunner -->
